https://www.{default}:
  type: upstream
  upstream: jekyll_app:http
https://www.{default}/submodule/:
  type: upstream
  upstream: jekyll_submodule:http
https://{default}:
  type: redirect
  to: https://www.{default}