name: jekyll_submodule
type: ruby:2.3
disk: 1024
web:
  locations:
    "/submodule":
      root: "platform-jekyll-submodule/_site"
      index:
        - index.html
      passthru: false
hooks:
  build: |
    gem install bundler
    cd platform-jekyll-submodule && bundle install
    jekyll build